version: "3"

services:
  nextjs-frontend-xcellfund:
    env_file:
      - .env
    image: nextjs-frontend-xcellfund:latest
    container_name: nextjs-frontend-xcellfund
    ports:
      - "1338:3000"
    restart: unless-stopped
